### ISSUE TITLE
Building fails

### ISSUE THREAD

**Issue by bertt** [javagl/cesium-cpp#2]
Hi, I'm trying to build this project, but getting 12 errors. Is the project up to date with Cesium Native?

![image](https://github.com/user-attachments/assets/8cb3f926-0932-4a53-9a4e-28cce4813edf)

**Comment by javagl** [comment]
Disclaimer: This is a pure spare-time project, not affiliated with Cesium in any way. 

And I'm not regularly updating it. I mainly used it for some experiments/debugging. So it was indeed not up to date with the latest state of `cesium-native`. However, in the spirit of being a toy project, I just made a highly professional commit (https://github.com/javagl/cesium-cpp/commit/95d0af2f800ea5f016aea6872f8de60ea9048729) directly into `master`. The _current_ state should work with the _current_ (still unreleased) state of `cesium-native`.

(I should probably include `cesium-native` as a submodule, so that it can be pinned to a 'tag' version or so... maybe, one day, when I have (too much) time...)

**Comment by bertt** [comment]
Thanks, got it working now :-)

![image](https://github.com/user-attachments/assets/e535fc81-b69d-462b-af50-a944ce8a9445)
